name: Mobile + Release
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: PsychEngine

jobs:
  build:
    name: Android
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y your-required-dependencies # reemplaza si es necesario

      - name: Build Android APK
        run: |
          haxelib run lime build android -final -D officialBuild

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@v4
        with:
           name: androidBuild
           path: /home/runner

      - name: Move Android File
        run: |
          APK_FILE=$(find /home/runner -name "*.apk" | head -n 1)
          mv "$APK_FILE" /home/runner/${{ env.PROJECT_NAME }}-Android.apk

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "0.6.3"
          tag_name: "0.6.3"
          prerelease: false
          files: /home/runner/*.apk
